# Generated by Django 3.2.3 on 2021-06-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slug', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coupon', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('expire_date', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('usage_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_customer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('information', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('store_inventory', models.IntegerField(default=0)),
                ('is_available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('rent_per_minute', models.IntegerField()),
                ('category', models.ManyToManyField(to='Homepage.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_table', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('current_capacity', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateTimeField()),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('is_employee', models.BooleanField()),
                ('is_owner', models.BooleanField()),
                ('Favorite_games', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_owner', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('tip', models.IntegerField()),
                ('how_to_pay', models.CharField(choices=[('cash', 'نقدی'), ('cart', 'کارت')], default='cash', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homepage.coupon')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.table')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.customer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.game')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=75, null=True)),
                ('sales_price', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_available', models.BooleanField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.basket')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.profile')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='games',
            field=models.ManyToManyField(through='Homepage.Game_Time', to='Homepage.Game'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.profile'),
        ),
        migrations.AddField(
            model_name='basket',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.coupon'),
        ),
        migrations.AddField(
            model_name='basket',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Homepage.customer'),
        ),
        migrations.AddField(
            model_name='basket',
            name='game_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.game_time'),
        ),
        migrations.AddField(
            model_name='basket',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.order'),
        ),
        migrations.AddField(
            model_name='basket',
            name='tables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.table'),
        ),
    ]
