# Generated by Django 3.2.3 on 2021-06-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
