# Generated by Django 3.2.3 on 2021-06-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_alter_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_time',
            name='number_of_players',
            field=models.IntegerField(default=1),
        ),
    ]
