# Generated by Django 3.2.3 on 2021-06-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_auto_20210608_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='id_table',
            new_name='table_number',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='id_coupon',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_order',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='id_owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
