# Generated by Django 3.2.3 on 2021-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_alter_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.IntegerField(default=1),
        ),
    ]
