# Generated by Django 3.2.3 on 2021-06-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_auto_20210609_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_employee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
