# Generated by Django 3.2.3 on 2021-06-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_auto_20210610_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='basket',
        ),
        migrations.CreateModel(
            name='BasketFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of', models.IntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.basket')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='basket',
            field=models.ManyToManyField(through='Homepage.BasketFood', to='Homepage.Basket'),
        ),
    ]
