# Generated by Django 3.2.3 on 2021-06-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_auto_20210610_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='game_time',
        ),
        migrations.AddField(
            model_name='game_time',
            name='basket',
            field=models.ManyToManyField(to='Homepage.Basket'),
        ),
        migrations.CreateModel(
            name='BasketGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of', models.IntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.basket')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.game')),
            ],
        ),
    ]
