# Generated by Django 3.2.3 on 2021-06-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
