# Generated by Django 3.2.3 on 2021-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_auto_20210623_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category_food',
        ),
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='purchase_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sales_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Category_Food',
        ),
    ]
