# Generated by Django 3.2.3 on 2021-06-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_alter_basket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='Homepage.order'),
        ),
    ]
