# Generated by Django 3.2.3 on 2021-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_auto_20210623_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
    ]
