# Generated by Django 3.2.3 on 2021-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_alter_basket_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='how_to_pay',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('cash,card', 'کارت و نقدی')], default='cash', max_length=10),
        ),
    ]
