# Generated by Django 3.2.3 on 2021-07-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_order_total_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remained_amount',
            field=models.IntegerField(default=0),
        ),
    ]
