# Generated by Django 3.2.3 on 2021-06-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_alter_order_how_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='tables',
        ),
    ]
