# Generated by Django 3.2.3 on 2021-06-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0013_remove_basket_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Amount_of_cash_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Card_payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
