# Generated by Django 3.2.3 on 2021-06-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0014_auto_20210614_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Homepage.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tip',
            field=models.IntegerField(default=0),
        ),
    ]
