# Generated by Django 3.2.3 on 2021-07-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0014_table_remaining_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_time',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
