# Generated by Django 3.2.3 on 2021-07-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0015_game_time_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketfood',
            name='value_food',
            field=models.IntegerField(default=0),
        ),
    ]
