# Generated by Django 3.2 on 2021-06-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0016_alter_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_line_item', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='basketfood',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketgame',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='food',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='game_time',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.AddField(
            model_name='line_item',
            name='basket_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.basketfood'),
        ),
        migrations.AddField(
            model_name='line_item',
            name='basket_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.basketgame'),
        ),
        migrations.AddField(
            model_name='line_item',
            name='game_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.game_time'),
        ),
        migrations.AddField(
            model_name='line_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.order'),
        ),
    ]
