# Generated by Django 3.2.3 on 2021-07-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0016_basketfood_value_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketgame',
            name='value_game',
            field=models.IntegerField(default=0),
        ),
    ]
