# Generated by Django 3.2.3 on 2021-07-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0017_basketgame_value_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='value_line_item',
            field=models.IntegerField(default=0),
        ),
    ]
