# Generated by Django 3.2 on 2021-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0017_auto_20210620_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='id_coupon',
            field=models.IntegerField(default=0),
        ),
    ]
